### PR TITLE
copyright year warning

### PR DESCRIPTION
**Pull request by tomByrer**
Not sure how to handle this, since some may not want their (c) year changed on them, or if the script is ran on a local Grunt/Gulp toolchain, it may falsely update the year.

Perhaps remove the year automation all together?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> some may not want their (c) year changed on them

Good point, I'll try to come up with something. It seems like the simplest thing would be to do what you're suggesting, but rather than removing the year automation from the existing banners we could just add a banner (or banners) without the year automation. what are your thoughts?

**Comment by jonschlinkert** [comment]
Also, thanks for creating this issue! I'll wait until we decide on an action before merging.

**Comment by tomByrer** [comment]
I've suggested hard-coding the year in before, on other repos that used Grunt.

**Comment by jonschlinkert** [comment]
The reason I created this repo was to dynamically update the copyright year on all of my repos (I have to update something like 250-300 repos on 4 different orgs), so that's not getting taken out. E.g. it's the only reason this is useful to me. 

So, I suggest we either:

A. Add more banners to choose from, or 
B. Add lodash as a dependency, allowing the banners to be included as mixins, rather than "just templates". This would allow us to add options to the banners. Essentially, it should work like this:

Instead of:

``` js
<%= banner.block %>
```

It might be something like this:

``` js
<%= _.banner(foo, bar, baz) %>
```

Or this:

``` js
<%= _.banner("block", false) %>
```

Where the first parameter is the banner to use, and the second parater, `false`, disables the date? It could also be an options object, e.g. `{date: false}`.

**Comment by tomByrer** [comment]
> The reason I created this repo was to dynamically update the copyright year on all of my repos (I have to update something like 250-300 repos on 4 different orgs)

Oh, sorry, I didn't know your use-case.  & my PR was long before I read your reply.
To me, simply warning it is dynamic is enough for now.  I'll change the PR to reflect that.

**Comment by tomByrer** [comment]
Fixed by rewrite; cheers.

**Comment by jonschlinkert** [comment]
:+1:

**Pull request closed without merging**
